[package]
name = "massa_sdk"
version = "0.24.0"
edition = "2021"

[dependencies]
jsonrpsee = { version = "0.20.0", features = ["client"] }
jsonrpsee-http-client = { version = "0.20.0", features = ["webpki-tls"] }
jsonrpsee-ws-client = { version = "0.20.0", features = ["webpki-tls"] }
http = "0.2.8"
tonic = { version = "0.9.1", features = ["gzip"] }
thiserror = "1.0"
tracing = {version =  "0.1", features = ["log"]}
massa_api_exports = { path = "../massa-api-exports" }
massa_models = { path = "../massa-models" }
massa_time = { path = "../massa-time" }
massa-proto-rs = { git = "https://github.com/massalabs/massa-proto-rs", rev = "18ec02f", features = ["tonic"] }
