[package]
name = "massa_api"
version = "0.24.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpsee = { version = "0.20.0", features = ["server", "macros"] }
futures = "0.3.18"
async-trait = "0.1.58"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.87"
tower-http = { version = "0.4.0", features = ["cors"] }
tower = { version = "0.4.13", features = ["full"] }
hyper = "0.14.25"
tokio = { version = "1.23", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tracing = "0.1"
itertools = "0.10"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
# custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_api_exports = { path = "../massa-api-exports" }
massa_models = { path = "../massa-models" }
massa_pool_exports = { path = "../massa-pool-exports" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_pos_exports = { path = "../massa-pos-exports" }
massa_storage = { path = "../massa-storage" }
massa_serialization = { path = "../massa-serialization" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_versioning = { path = "../massa-versioning" }
massa_hash = { path = "../massa-hash" }
massa_wallet = { path = "../massa-wallet" }
